### ISSUE TITLE
Problem querying Rest API

### ISSUE THREAD

**Issue by adamchadwick** [BCDevExchange/garbage-day#11]
Access the Rest API here:  http://geoprodsvr.kamloops.ca:6080/arcgis/rest/services/BCDevExchange/GarbagePickup/MapServer

From there select the GIST_Garbage_Schedule link. Review the schema columns at the bottom of the page: ObjectId, Address, Zone. Select the Query link and enter the following values:

Where: ADDRESS = ‘348 TRANQUILLE RD’
Out Fields: Address, Zone

Select the Query (GET) button at the bottom of the page and see the Address and Zone displayed for that address. Do the same for GIST_Garbage_Zone except for the different column names.

This is how to do it through the interface – I don’t know how to do it programmatically however there’s help online here http://resources.arcgis.com/en/help/rest/apiref/ (Ps. we’re running AGS version 10.2.1 if that makes a difference).

Note that the Rest API url will undergo change likely Tue eve (if all goes well) - I will update the url in the docs.

Sorry, gone for the next 5 days.

**Comment by jsjb** [comment]
Note that **[GIST_Garbage_Zone](http://geoprodsvr.kamloops.ca:6080/arcgis/rest/services/BCDevExchange/GarbagePickup/MapServer/3)** has the _'Address'_ column, and **[GIST_Garbage_Schedule](http://geoprodsvr.kamloops.ca:6080/arcgis/rest/services/BCDevExchange/GarbagePickup/MapServer/2)** instead has _'PickupDate'_, so they should be switched in your explanation.

**Comment by adamchadwick** [comment]
Corrected below:

Access the Rest API here: http://geoprodsvr.kamloops.ca:6080/arcgis/rest/services/BCDevExchange/GarbagePickup/MapServer

From there select the GIST_Garbage_Zone link. Review the schema columns at the bottom of the page: ObjectId, Address, Zone. Select the Query link and enter the following values:

Where: ADDRESS = ‘348 TRANQUILLE RD’
Out Fields: Address, Zone

Select the Query (GET) button at the bottom of the page and see the Address and Zone displayed for that address. Do the same for GIST_Garbage_Schedule except for the different column names.

This is how to do it through the interface – I don’t know how to do it programmatically however there’s help online here http://resources.arcgis.com/en/help/rest/apiref/ (Ps. we’re running AGS version 10.2.1 if that makes a difference).

Note that the Rest API url will undergo change likely Tue eve (if all goes well) - I will update the url in the docs

**Comment by jordanrinke** [comment]
This has been tested and confirmed working. Some details still need to be worked out in documentation - but it is functioning as needed.
