### ISSUE TITLE
A user can go to the garbage day website

### ISSUE THREAD

**Issue by jordanrinke** [BCDevExchange/garbage-day#16]
- [ ] Provide a page where users can go by pasting a link to their address bar.
- [ ] Users will see a text field with a "Enter your address and click "Search"" text prompt beside a "Search" button making it clear the user needs to enter their address into the text field.
- [ ] Display a map that shows the zones on the page.

**Comment by adamchadwick** [comment]
Do we really need to display a map? Can't we isolate the subscriber from having to know their zone. I think all the subscriber needs to know is their address and when and what type of reminder they want. I think the zone issue can be made transparent therefore making the application appear more user friendly/less technical.

For address lookup take a look at what we've done at www.kamloops.ca/propertyinfo. Enter the house number and start to enter the street name and then pause - you'll see the list of validly matching addresses narrowed as you continue to enter the address. This is just one way of doing this but an example nonetheless.

**Comment by cnewallbcgov** [comment]
The Province of BC offers an auto-complete widget that calls the BC Physical Address Geocoding web service.  It can be found here:  http://apps.gov.bc.ca/pub/geocoder/geo/widget

For more info on the Geocoder: http://www.data.gov.bc.ca/dbc/geographic/locate/geocoding.page

**Comment by jordanrinke** [comment]
@adamchadwick Yeah, the idea was that the map would provide a nice background for the site pending it having more actual content. The main landing/splash page.
